name: "Check pull request title"
description: "Github action to check Pull Request title based on JS Regexp"
author: "Slashgear_"
inputs:
  regexp:
    description: "Regexp (as String) to validate the pull request title"
    required: false
    default: "([A-Z][A-Z0-9_]+-[1-9][0-9]*|TRIVIAL|[mM]erge)"
  flags:
    description: "Regexp flags of the object."
    required: false
    default: ""
  helpMessage:
    description: "Help message displayed in the action execution logs to help the user understand how to correct the title of the Pull Request."
    required: false
    default: "Example: 'KORE-859: foo'"
  jiraUrl:
    description: "JIRA API url"
    required: false
    default: ""
  jiraUsername:
    description: "JIRA API username"
    required: false
    default: ""
  jiraToken:
    description: "JIRA API token"
    required: false
    default: ""
  jiraSkipCheck:
    description: "Skip check for JIRA parent ID for these IDs (comma separated)"
    required: false
    default: "merge,trivial"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "type"
  color: "gray-dark"
